version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip function.zip lambda_functions.py
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
