version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies (if any)..."
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip function.zip lambda_functions.py
artifacts:
  files:
    - function.zip
